window.GYU_DEFAULT_CONFIG = {
  meta: {
    title: "생일축하합니다",
    slug: "default",
  },
  colors: {
    bg: "#fff9c4",
    yesBg: "#ffb6c8",
  },
  texts: {
    hello: "안녕하세요...",
    question: "생일축하합니다: 생일자 본인이 맞습니까?",
    yes: "예!",
    no: "아뇨?",
    modal: "왜 들어옴? 나가세요",
    wait: "잠시만요 ㅠㅠ",
  },
  images: {
    main: { src: "assets/images/cat1.svg", width: 190 },
    modal: { src: "assets/images/cat2.svg", width: 170 },
    feet: { src: "assets/images/feet.svg", width: 204 },
    yesHero: { src: "assets/images/image.png", width: 300 },
    usagi: { src: "assets/images/usagi.png", width: 120 },
    wander: { src: "assets/images/IMG_6639.JPG", width: 140 },
    tearBottom: { src: "assets/images/image-copy-6.png", width: 300 },
  },
  sounds: {
    hello: "assets/sounds/vine-boom.mp3",
    no: "assets/sounds/ceeday-huh-sound-effect.mp3",
    wait: "assets/sounds/ice-cream_IxY1RUr.mp3",
    bgm: "assets/sounds/send-online-audio-converter.mp3",
    nya: "assets/sounds/nya_ZtXOXLx.mp3",
    usagi: "assets/sounds/usagi-yahaaaaaa.mp3",
    punch: "assets/sounds/punch_u4LmMsr.mp3",
    tuco: "assets/sounds/tuco-get-out.mp3",
  },
  timing: {
    kickDelayMs: 1600,
    yesIntroDelayMs: 4000,
    slideIntervalMs: 4000,
    usagiIntervalMs: 500,
    usagiCount: 3,
    usagiExtraCount: 2,
    nyaCount: 2,
    waitAfterPulses: 4,
    footCycleMs: 720,
  },
  features: {
    fireworks: true,
    usagi: true,
    wander: true,
    nyaTwice: true,
  },
  slides: [
    {
      text: "여보 생일축하해 ㅎㅎ",
      image: "assets/images/cat2.svg",
      width: 280,
      anim: "spin",
      sound: "",
      bottomImage: "",
      bottomWidth: 220,
      bgColor: "#ffb6c8",
      fontSize: 28,
      fontColor: "#ffffff",
      textEffect: "glow",
      delaySec: 4,
    },
    {
      text: "늘 나 잘 챙겨줘서 넘 고마워",
      image: "assets/images/IMG_6640.JPG",
      width: 280,
      anim: "spin",
      sound: "",
      bottomImage: "",
      bottomWidth: 220,
      bgColor: "#ffb6c8",
      fontSize: 28,
      fontColor: "#ffffff",
      textEffect: "glow",
      delaySec: 4,
    },
    {
      text: "우리 오래오래 잘 만나자",
      image: "assets/images/IMG_0264.JPG",
      width: 280,
      anim: "spin",
      sound: "",
      bottomImage: "",
      bottomWidth: 220,
      bgColor: "#ffb6c8",
      fontSize: 28,
      fontColor: "#ffffff",
      textEffect: "glow",
      delaySec: 4,
    },
    {
      text: "비록 우리가 지금은 좀 멀리 있지만...",
      image: "assets/images/image-copy.png",
      width: 300,
      anim: "fade",
      sound: "",
      bottomImage: "",
      bottomWidth: 220,
      bgColor: "#ffb6c8",
      fontSize: 24,
      fontColor: "#ffffff",
      textEffect: "shadow",
      delaySec: 4,
    },
    {
      text: "내가 많이 축하해",
      image: "assets/images/image-copy-2.png",
      width: 320,
      anim: "boom",
      sound: "assets/sounds/tadaaa.mp3",
      bottomImage: "",
      bottomWidth: 220,
      bgColor: "#ff9eb5",
      fontSize: 36,
      fontColor: "#fff45a",
      textEffect: "hyper",
      delaySec: 4,
    },
    {
      text: "나도 더 좋은 사람이 되도록 할게",
      image: "assets/images/image-copy-3.png",
      width: 280,
      anim: "spin",
      sound: "",
      bottomImage: "",
      bottomWidth: 220,
      bgColor: "#ffb6c8",
      fontSize: 26,
      fontColor: "#ffffff",
      textEffect: "glow",
      delaySec: 4,
    },
    {
      text: "많이사랑해 ㅎㅎ",
      image: "assets/images/image-copy-4.png",
      width: 300,
      anim: "hyper",
      sound: "assets/sounds/applause_2.mp3",
      bottomImage: "",
      bottomWidth: 220,
      bgColor: "#ff8fb3",
      fontSize: 40,
      fontColor: "#fff45a",
      textEffect: "hyper",
      delaySec: 4,
    },
    {
      text: "(이제 감동의 눈물을 흘릴 타이밍)",
      image: "assets/images/image-copy-5.png",
      width: 300,
      anim: "tear",
      sound: "assets/sounds/cry-banana-cat.mp3",
      bottomImage: "assets/images/image-copy-6.png",
      bottomWidth: 220,
      bgColor: "#ffb6c8",
      fontSize: 20,
      fontColor: "#ffffff",
      textEffect: "soft",
      delaySec: 4,
    },
  ],
};
